# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags: "-s -w -X gitlab.in2p3.fr/cc-in2p3-puppet-master-tools/puppet-modulator/version.Version={{.Version}} -X gitlab.in2p3.fr/cc-in2p3-puppet-master-tools/puppet-modulator/version.Commit={{.Commit}} -X gitlab.in2p3.fr/cc-in2p3-puppet-master-tools/puppet-modulator/version.BuildDate={{.Date}}"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# Generate DEB and RPM using NFPM
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}'
    homepage: https://gitlab.in2p3.fr/cc-in2p3-puppet-master-tools/puppet-modulator
    description: Standalone substitute to https://github.com/voxpupuli/puppet-blacksmith
    maintainer: Remi Ferrand <remi.ferrand@cc.in2p3.fr>
    license: CeCILL-B
    vendor: CC-IN2P3
    formats:
      - apk
      - deb
      - rpm
    bindir: '/usr/bin'

#
# Gitlab integration
#
gitlab_urls:
  api: https://gitlab.in2p3.fr/api/v4/
  download: https://gitlab.in2p3.fr

env_files:
  gitlab_token: '~/.config/goreleaser/gitlab.in2p3.fr/gitlab_token'
