---
# Complete example: https://gitlab.cern.ch/abpcomputing/abpcpweb/-/blob/master/mkdocs.yml
# http://abpcomputing.web.cern.ch/abpcp/
site_name: Puppet Modulator
site_description: "Quickly edit your Puppet modules metadata.json and wrap your git and git-flow workflows"
site_url: https://github.com/ccin2p3/puppet-modulator
copyright: "Copyright &copy; 2021 IN2P3 Computing Centre, IN2P3, CNRS"

repo_name: Github
repo_url: https://github.com/ccin2p3/puppet-modulator
edit_uri: "tree/develop/docs/content/"

docs_dir: "content"

extra_css:
  - stylesheets/extra.css
  - "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"

extra_javascript:
  - "js/matomo.js"

dev_addr: "127.0.0.1:8000"

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true

theme:
  name: "material"
  custom_dir: overrides
  logo: "images/modulator-logo-small.png"
  favicon: images/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.top
    - toc
    #- navigation.instant
  palette:
    - media: "(prefers-color-scheme: dark)" # Dark mode
      scheme: slate
      primary: light blue
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)" # Light mode
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

plugins:
  - minify:
      minify_html: true

extra:
  social:
    - name: "IN2P3 Computing Centre"
      icon: "images/ccin2p3_logo.png"
      link: "https://cc.in2p3.fr/en/"

nav:
  - Home: "index.md"
  - Install: "install.md"
  - Requirements: "requirements.md"
  - Getting started:
      - Alias: "quickstart/alias.md"
      - Metadata manipulation: "quickstart/metadata.md"
  - Metadata command:
      - Usage and commit policies: "metadata/index.md"
      - Module version: "metadata/version.md"
      - Puppet version requirements: "metadata/puppet-requirements.md"
  - Flow command: "flow.md"
  - F.A.Q: "faq.md"
